crm/crm/urls.py
from django.conf.urls import url
from django.contrib import admin

from crm01 import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #首页
    url(r'^index/',views.index,name='index'),
    #注册
    url(r'^register/',views.register,name='register'),
    #登录
    url(r'^login/',views.login,name='login'),
    #验证码
    url(r'^get_valid_img/',views.get_valid_img,name='get_valid_img'),
    #注销
    url(r'^logout/',views.logout,name='logout'),
    #展示公户信息
    url(r'^customers/list/', views.CustomerView.as_view(), name='customers'),
    #展示私户信息
    url(r'^mycustomers/', views.MyCustomerView.as_view(), name='mycustomers'),
    #展示客户跟进记录
    url(r'^Follow_Up_Records/$', views.Follow_Up_Records.as_view(), name='Follow_Up_Records'),
    #公户页面显示跟进记录
    url(r'^Follow_Up_Records/(\d+)$', views.Follow_Up_Records.as_view(), name='DanGe_Follow_Up_Records'),
    #展示客户跟进 添加记录
    url(r'^Follow_Up_Records/add/', views.AddFollow_Up_Records.as_view(), name='addFollow_Up_Records'),
    #编辑跟进记录
    url(r'^Follow_Up_Records/edit/(\d+)', views.EditFollow_Up_Records.as_view(), name='editFollow'),

    #测试分页
    # url(r'^test/', views.test, name='test'),
    #添加信息
    url(r'^customers/add/',views.AddCustomer.as_view(),name='addcustomer'),
    #编辑信息
    url(r'^customers/edit/(\d+)/',views.Editcustomer.as_view(),name='editcustomer'),
    #删除信息
    url(r'^customers/del/(\d+)/',views.Delcustomer.as_view(),name='delcustomer'),

]

crm/crm01/models.py
# from django.db import models
# from django.contrib.auth.models import AbstractUser #用继承的方式创建 用户表 先引入
# # Create your models here.
#
# class UserInfo(AbstractUser):
#
#     telephone = models.CharField(max_length=32,null=True)  #项目中 电话号码设成字符串形式 便于后期查找：filter(telephone_startswith = '159')





from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser


from django.db import models
from django.contrib import auth
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager, User
from django.utils.translation import ugettext_lazy as _
from multiselectfield import MultiSelectField
#安装:pip install django-multiselectfield,针对choices多选用的

from django.utils.safestring import mark_safe

course_choices = (('LinuxL', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)

class UserInfo(AbstractUser):
    #销售,班主任,讲师,三哥
    telephone = models.CharField(max_length=32,null=True)


class Customer(models.Model):
    """
    客户表（最开始的时候大家都是客户，销售就不停的撩你，你还没交钱就是个客户）
    """
    qq = models.CharField(verbose_name='QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True) #存的是male或者female，字符串
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)

    phone = models.CharField('手机号', blank=True, null=True,max_length=32)
    # phone = models.CharField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')

    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True)  #self指的就是自己这个表，和下面写法是一样的效果


    # introduce_from = models.ForeignKey('Customer', verbose_name="转介绍自学员", blank=True, null=True,on_delete=models.CASCADE)
    course = MultiSelectField("咨询课程", choices=course_choices) #多选，并且存成一个列表的格式
    # course = models.CharField("咨询课程", choices=course_choices) #如果你不想用上面的多选功能，可以使用Charfield来存
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",help_text="选择客户此时的状态") #help_text这种参数基本都是针对admin应用里面用的

    date = models.DateTimeField("咨询日期", auto_now_add=True)

    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True) #考核销售的跟进情况，如果多天没有跟进，会影响销售的绩效等
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True) #销售自己大概记录一下自己下一次会什么时候跟进，也没啥用

    #用户表中存放的是自己公司的所有员工。
    consultant = models.ForeignKey('UserInfo', verbose_name="销售", blank=True, null=True)


    #一个客户可以报多个班，报个脱产班，再报个周末班等，所以是多对多。
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", )


    def __str__(self):
        return self.name+":"+self.qq  #主要__str__最好是个字符串昂，不然你会遇到很多的坑，还有我们返回的这两个字段填写数据的时候必须写上数据，必然相加会报错，null类型和str类型不能相加等错误信息。


    def get_classlist(self):  #当我们通过self.get_classlist的时候，就拿到了所有的班级信息，前端显示的时候用

        l=[]
        for cls in self.class_list.all():
            l.append(str(cls))
        # return mark_safe(",".join(l)) #纯文本，不用mark_safe也可以昂
        return ",".join(l) #纯文本，不用mark_safe也可以昂


class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name




class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期") #python20期等
    campuses = models.ForeignKey('Campuses', verbose_name="校区",on_delete=models.CASCADE)
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True) #不一定什么时候结业，哈哈，所以可为空

    #contract = models.ForeignKey('ContractTemplate', verbose_name="选择合同模版", blank=True, null=True,on_delete=models.CASCADE)
    teachers = models.ManyToManyField('UserInfo', verbose_name="老师") #对了，还有一点，如果你用的django2版本的，那么外键字段都需要自行写上on_delete=models.CASCADE

    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')

    def __str__(self):
        return "{}{}({})".format(self.get_course_display(), self.semester, self.campuses)



class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户")

    note = models.TextField(verbose_name="跟进内容...")

    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")

    consultant = models.ForeignKey("UserInfo", verbose_name="跟进人", related_name='records')

    date = models.DateTimeField("跟进日期", auto_now_add=True)

    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

crm/templates/Follow_Up_Records.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                客户跟进记录
                <small>展示</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                <li class="active">Here</li>
            </ol>
        </section>
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                        <form action="" method="get" class="pull-right" style="width: 400px;display: inline-block">
                            <select name="condition" id="" class="form-control" style="width: 110px;display: inline-block">
                                <option value="name__contains">咨询客户</option>
                            </select>
                            <input type="text" name="wd" class="form-control" style="width: 200px;display: inline-block"> <button class="btn btn-default">搜索</button>
                        </form>
                        <a href="{% url 'addFollow_Up_Records' %}" class="btn btn-primary pull-right">添加记录</a>
                     <form action="" method="post" >
                            {% csrf_token %}
                            <select name="action" id="" class="form-control" style="width: 200px;display: inline-block">
{#                                <option value="batch_del">批量删除</option>#}
                                <option value="batch_update">批量更新跟进记录</option>
                            </select>
                            <button class="btn btn-danger" style="vertical-align: 1px;">go</button>

                        <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>
                                    <input type="checkbox" id="choose">
                                </th>
                                <th>序号</th>
                                <th>咨询客户</th>
                                <th>跟进内容</th>
                                <th>跟进状态</th>
                                <th>跟进人</th>
                                <th>跟进日期</th>
                                <th>操作</th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for records in all_records %}
                                    <tr>
                                        <td><input type="checkbox" name="selected_id" value="{{ records.pk }}"></td>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ records.customer }}</td>
                                        <td>{{ records.note }}</td>
                                        <td>{{ records.get_status_display }}</td>
                                        <td>{{ records.consultant.username }}</td>
                                        <td>{{ records.date|date:'Y-m-d' }}</td>
                                        <td>
                                            <a href="{% url 'editFollow' records.pk %}" class="btn btn-warning btn-xs">编辑</a>
{#                                            <a href="{% url 'delcustomer' records.pk %}" class="btn btn-danger btn-xs">删除</a>#}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                     </form>
                </div>
            </div>
        </div>
    </section>

    {{ ret_html|safe }}
    </div>
{% endblock %}
{#全选#}
{% block js %}
    <script>
        $('#choose').click(function(){
        var status = $(this).prop('checked');
        $('[name=selected_id]').prop('checked',status);
        })
    </script>

{% endblock %}




{#{% block content %}#}
{#    <div class="content-wrapper">#}
{##}
{#        <section class="content-header">#}
{#            <h1>#}
{#                客户跟进信息#}
{#                <small>展示</small>#}
{#            </h1>#}
{##}
{#            <ol class="breadcrumb">#}
{#                <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>#}
{#                <li class="active">Here</li>#}
{#            </ol>#}
{#        </section>#}
{##}
{#    <section class="content container-fluid">#}
{#        <div class="row">#}
{#            <div class="col-xs-12">#}
{#                <div class="box">#}
{##}
{##}
{#                        <form action="" method="get" class="pull-right" style="width: 400px;display: inline-block">#}
{#                            <select name="condition" id="" class="form-control" style="width: 100px;display: inline-block">#}
{#                                <option value="name__contains">姓名</option>#}
{#                                <option value="qq__contains">QQ</option>#}
{#                            </select>#}
{#                            <input type="text" name="wd" class="form-control" style="width: 200px;display: inline-block"> <button class="btn btn-default">搜索</button>#}
{#                        </form>#}
{#                        <a href="{% url 'addcustomer' %}" class="btn btn-primary pull-right">添加记录</a>#}
{##}
{#                     <form action="{% url 'Follow_Up_Records' %}" method="post" >#}
{#                            {% csrf_token %}#}
{#                            <select name="action" id="" class="form-control" style="width: 200px;display: inline-block">#}
{#                                <option value="batch_del">批量删除</option>#}
{#                                <option value="batch_update">批量更新客户状态</option>#}
{#                            <option value="batch_g_s">公户转私户</option>#}
{##}
{#                            </select>#}
{#                            <button class="btn btn-danger" style="vertical-align: 1px;">go</button>#}
{##}
{#                        <div class="box-body">#}
{#                        <table id="example2" class="table table-bordered table-hover">#}
{#                            <thead>#}
{#                            <tr>#}
{#                                <th>#}
{#                                    <input type="checkbox" id="choose">#}
{#                                </th>#}
{#                                <th>序号</th>#}
{#                                <th>qq</th>#}
{#                                <th>姓名</th>#}
{#                                <th>性别</th>#}
{#                                <th>客户来源</th>#}
{#                                <th>咨询课程</th>#}
{#                                <th>跟进记录</th>#}
{#                                <th>销售</th>#}
{#                                <th>操作</th>#}
{#                            </tr>#}
{#                            </thead>#}
{#                            <tbody>#}
{#                                {% for mycustomer in all_my_customers %}#}
{#                                    <tr>#}
{#                                        <td><input type="checkbox" name="selected_id" value="{{ mycustomer.pk }}"></td>#}
{#                                        <td>{{ forloop.counter }}</td>#}
{#                                        <td>{{ mycustomer.qq }}</td>#}
{#                                        <td>{{ mycustomer.name }}</td>#}
{#                                        <td>{{ mycustomer.get_sex_display }}</td>#}
{#                                        <td>{{ mycustomer.get_source_display }}</td>#}
{#                                        <td>{{ mycustomer.course }}</td>#}
{#                                        <td><a href="{% url 'Follow_Up_Records' %}">跟进记录</a> </td>#}
{#                                        <td>{{ mycustomer.consultant.username}}</td>#}
{#                                        <td>#}
{#                                            <a href="{% url 'editcustomer' mycustomer.pk %}" class="btn btn-warning btn-xs">编辑</a>#}
{#                                            <a href="{% url 'delcustomer' mycustomer.pk %}" class="btn btn-danger btn-xs">删除</a>#}
{#                                        </td>#}
{#                                    </tr>#}
{#                                {% endfor %}#}
{##}
{#                            </tbody>#}
{#                        </table>#}
{#                    </div>#}
{#                     </form>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </section>#}
{##}
{#    {{ ret_html|safe }}#}
{#    </div>#}
{#{% endblock %}#}
{#全选#}
{#{% block js %}#}
{#    <script>#}
{#        $('#choose').click(function(){#}
{#        var status = $(this).prop('checked');#}
{#        $('[name=selected_id]').prop('checked',status);#}
{#        })#}
{#    </script>#}
{##}
{#{% endblock %}#}
{##}

crm/templates/addFollow_Up_Records.html
{% extends 'base.html' %}

{% block content %}

        <div class="content-wrapper">
        <section class="content-header">
            <h1>
                跟进记录
                <small>展示</small>
            </h1>

            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                <li class="active">Here</li>
            </ol>
        </section>
        <section class="content container-fluid">
                <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="{% url 'addFollow_Up_Records' %}" method="post" novalidate >
                {%csrf_token%}
                    {% for field in form_obj %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                            <span class="text-danger">{{ field.errors.0 }}</span>
                        </div>
                {% endfor %}
                <button   class="btn btn-primary pull-right">提交</button>
                </form>
            </div>
        </div>
    </div>
        </section>
    </div>


{% endblock %}

crm/templates/addcustomer.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-wrapper">
            <section class="content-header">
            <h1>
                添加页面
                <small>Addition</small>
            </h1>

            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                <li class="active">Here</li>
            </ol>
        </section>
         <section class="content container-fluid">
             <div class="container-fluid">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <form  action="{% url 'addcustomer' %}" method="post" novalidate>
                        {%csrf_token%}
                            {% for field in form_obj %}
                                <div class="form-group">
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {{ field }}
                                    <span class="text-danger">{{ field.errors.0 }}</span>
                                </div>
                        {% endfor %}
                        <button class="btn btn-primary pull-right">提交</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

crm/templates/customers.html
{% extends 'base.html' %}

{% block content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->

        <section class="content-header">
            <h1>
                公共客户信息
                <small>展示</small>
            </h1>

            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                <li class="active">Here</li>
            </ol>
        </section>

    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">


                        <form action="" method="get" class="pull-right" style="width: 400px;display: inline-block">
                            <select name="condition" id="" class="form-control" style="width: 100px;display: inline-block">
                                <option value="name__contains">姓名</option>
                                <option value="qq__contains">QQ</option>
                            </select>
                            <input type="text" name="wd" class="form-control" style="width: 200px;display: inline-block"> <button class="btn btn-default">搜索</button>
                        </form>
                        <a href="{% url 'addcustomer' %}" class="btn btn-primary pull-right">添加记录</a>

                     <form action="{% url 'customers' %}" method="post" >
                            {% csrf_token %}
                            <select name="action" id="" class="form-control" style="width: 200px;display: inline-block">
                                <option value="batch_del">批量删除</option>
                                <option value="batch_update">批量更新客户状态</option>
                            <option value="batch_g_s">公户转私户</option>

                            </select>
                            <button class="btn btn-danger" style="vertical-align: 1px;">go</button>

                        <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>
                                    <input type="checkbox" id="choose">
                                </th>
                                <th>序号</th>
                                <th>qq</th>
                                <th>姓名</th>
                                <th>性别</th>
                                <th>客户来源</th>
                                <th>咨询课程</th>
                                <th>选择客户此时的状态</th>
                                <th>销售</th>
                                <th>跟进记录</th>
                                <th>操作</th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for customer in all_customers %}
                                    <tr>
                                        <td><input type="checkbox" name="selected_id" value="{{ customer.pk }}"></td>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ customer.qq }}</td>
                                        <td>{{ customer.name }}</td>
                                        <td>{{ customer.get_sex_display }}</td>
                                        <td>{{ customer.get_source_display }}</td>
                                        <td>{{ customer.course }}</td>
                                        <td>{{ customer.get_status_display }}</td>
                                        <td>{{ customer.consultant.username|default:'暂无' }}</td>
                                        <td><a href="{% url 'DanGe_Follow_Up_Records' customer.pk %}">跟进记录</a> </td>

                                        <td>
                                            <a href="{% url 'editcustomer' customer.pk %}" class="btn btn-warning btn-xs">编辑</a>
                                            <a href="{% url 'delcustomer' customer.pk %}" class="btn btn-danger btn-xs">删除</a>
                                        </td>
                                    </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>
                     </form>
                </div>
            </div>
        </div>
    </section>

    {{ ret_html|safe }}
    </div>
{% endblock %}
{#全选#}
{% block js %}
    <script>
        $('#choose').click(function(){
        var status = $(this).prop('checked');
        $('[name=selected_id]').prop('checked',status);
        {#if (status === true){#}
        {#    $('[name=selected_id]').prop('checked',true);#}
        {##}

        {#else{#}
        {#    $('[name=selected_id]').prop('checked',false);#}
    })
    </script>

{% endblock %}

crm/templates/editFollow.html
{% extends 'base.html' %}

{% block content %}

        <div class="content-wrapper">
        <section class="content-header">
            <h1>
                跟进记录编辑
                <small>展示</small>
            </h1>

            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                <li class="active">Here</li>
            </ol>
        </section>
        <section class="content container-fluid">
                <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="" method="post" novalidate >
                {%csrf_token%}
                    {% for field in form_obj %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                            <span class="text-danger">{{ field.errors.0 }}</span>
                        </div>
                {% endfor %}
                <button   class="btn btn-primary pull-right">提交</button>
                </form>
            </div>
        </div>
    </div>
        </section>
    </div>


{% endblock %}

crm/templates/mycustomers.html
{% extends 'base.html' %}

{% block content %}
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                我的客户信息
                <small>展示</small>
            </h1>

            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                <li class="active">Here</li>
            </ol>
        </section>
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                        <form action="" method="get" class="pull-right" style="width: 400px;display: inline-block">
                            <select name="condition" id="" class="form-control" style="width: 100px;display: inline-block">
                                <option value="name__contains">姓名</option>
                                <option value="qq__contains">QQ</option>
                            </select>
                            <input type="text" name="wd" class="form-control" style="width: 200px;display: inline-block"> <button class="btn btn-default">搜索</button>
                        </form>
{#                        <a href="{% url 'addcustomer' %}" class="btn btn-primary pull-right">添加记录</a>#}

                     <form action="" method="post" >
                            {% csrf_token %}
                            <select name="action" id="" class="form-control" style="width: 200px;display: inline-block">
{#                                <option value="batch_del">批量删除</option>#}
                                <option value="batch_update">批量更新客户状态</option>
                            <option value="batch_s_g">私户转公户</option>

                            </select>
                            <button class="btn btn-danger" style="vertical-align: 1px;">go</button>

                        <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>
                                    <input type="checkbox" id="choose">
                                </th>
                                <th>序号</th>
                                <th>qq</th>
                                <th>姓名</th>
                                <th>性别</th>
                                <th>客户来源</th>
                                <th>咨询课程</th>
                                <th>跟进记录</th>
                                <th>销售</th>
                                <th>操作</th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for mycustomer in all_my_customers %}
                                    <tr>
                                        <td><input type="checkbox" name="selected_id" value="{{ mycustomer.pk }}"></td>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ mycustomer.qq }}</td>
                                        <td>{{ mycustomer.name }}</td>
                                        <td>{{ mycustomer.get_sex_display }}</td>
                                        <td>{{ mycustomer.get_source_display }}</td>
                                        <td>{{ mycustomer.course }}</td>
                                        <td><a href="{% url 'DanGe_Follow_Up_Records' mycustomer.pk%}">跟进记录</a> </td>
                                        <td>{{ mycustomer.consultant.username}}</td>
                                        <td>
                                            <a href="{% url 'editcustomer' mycustomer.pk %}" class="btn btn-warning btn-xs">编辑</a>
                                            <a href="{% url 'delcustomer' mycustomer.pk %}" class="btn btn-danger btn-xs">删除</a>
                                        </td>
                                    </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>
                     </form>
                </div>
            </div>
        </div>
    </section>

    {{ ret_html|safe }}
    </div>
{% endblock %}
{#全选#}
{% block js %}
    <script>
        $('#choose').click(function(){
        var status = $(this).prop('checked');
        $('[name=selected_id]').prop('checked',status);
        })
    </script>

{% endblock %}